# Production profile - for Docker
server.port=8080

# In Docker the app-service host will be the service name defined in docker-compose (ej: app-service)
# Ajusta la URI según el nombre del servicio/stack
spring.cloud.gateway.routes[0].id=app-service
spring.cloud.gateway.routes[0].uri=http://app-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

# Disable devtools
spring.devtools.restart.enabled=false

