# Development profile - local wiring
server.port=8080

# Ruta del gateway hacia el backend local (puedes dejar http://localhost:8081 cuando ejecutas app-service localmente)
spring.cloud.gateway.routes[0].id=app-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/**

# Habilitar devtools behavior si está presente
spring.devtools.restart.enabled=true

